import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import { TopNav } from "./_components/top-nav";
import "./globals.css";
import { TopNavNext } from "./_components/top-nav-next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavNext />
        {children}
        <Script src="https://accounts.google.com/gsi/client" async={true} strategy="beforeInteractive"></Script>
      </body>
    </html>
  );
}
